# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MGWR
                                 A QGIS plugin
 A QGIS plugin for Multiscale Geographically Weighted Regression (MGWR)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-05
        copyright            : (C) 2024 by Huaying Gu & Yi Wu
        email                : aaron.yiwu15@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Huaying Gu & Yi Wu'
__date__ = '2024-05-05'
__copyright__ = '(C) 2024 by Huaying Gu & Yi Wu'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MGWR class from file MGWR.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MGWR_Plugin import MGWRPlugin
    return MGWRPlugin(iface)
